In [1]:
pip install numpy # install package

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
np1=np.array([1,2,3])
np1

array([1, 2, 3])

In [4]:
np2=np.array([[1,2,3],[4,5,6]])
np2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np3=np.array([[1,2,3,],[4,5,6]])

In [6]:
np.zeros(3)


array([0., 0., 0.])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.empty(3)

array([0., 0., 0.])

In [10]:
np.arange(1,3,1)

array([1, 2])

In [11]:
np.arange(1,15,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr=([1,2,2])
np.sort(arr)

array([1, 2, 3])

In [14]:
type(np1)

numpy.ndarray

In [30]:
np1=np.array([[5,6,7],[2,4,5]])
np2=np.array([9,5,6])
np.concatenate(((np1,np2)),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [32]:
arr1=np.array([[[1,2,3],[3,4,5],[2,3,4]]] )
arr2=np.array([[[4,5,6],[7,8,9],[1,2,3]]] )
arr3=np.array([[[5,2,8],[7,8,9],[4,5,8]]] )
np.concatenate(((arr1,arr2,arr3)),axis=0)

array([[[1, 2, 3],
        [3, 4, 5],
        [2, 3, 4]],

       [[4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]],

       [[5, 2, 8],
        [7, 8, 9],
        [4, 5, 8]]])

In [39]:
arr3.size

9

In [40]:
arr3.ndim

3

In [43]:
arr3=arr3.reshape(3,2,1)

ValueError: cannot reshape array of size 9 into shape (3,2,1)

In [45]:
arr2.shape

(1, 3, 3)

In [1]:
import numpy as np


array=np.array([1,2,3])#creating datasheet
np.save("numpy",array)
np.load("numpy.npy")

array([1, 2, 3])

In [15]:
value=pd.DataFrame(array)

ValueError: Must pass 2-d input. shape=(1, 3, 3)

In [2]:
import pandas as pd 
pip install pandas

SyntaxError: invalid syntax (586875914.py, line 2)

In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# step of pandas 
1 install pandas librarys- pip 
2. import pandas - 
3. create np array
4. convert np array into pd.DataFrame
5. save it as csv-pd.to_csv("csv filename")
6. read csv into variable - read csv("csv file")
7.print

In [ ]:
deep learning -neural network
ml=supervised learning,unsupervised learning,reinforcement
AI/ML domains-computer vision(cv)[image ,video],Natural language processing(NLP)[audio,text],Statistcal Data(history data)[record,csv,excell sheet]

learning code:
    no-code approach:- No-code tools[Teachable Machine]
    low-code approach
    coding approach